### ISSUE TITLE
js_cc_scroll_to_error.html5 und Formularversand mit Ajax funktioniert nicht

### ISSUE THREAD

**Issue by Schmidty2** [heimseiten/contao-custom-contao-bundle#1]
Hallo,
das Skript js_cc_scroll_to_error.html5 funktioniert nicht, wenn im Formular die Option "Per Ajax senden" aktiviert ist.
Wenn man "Per Ajax senden" im Formular deaktiviert, funktioniert das Scrollen zum fehlerhaften Feld wieder.
Getestet mit Contao 5.3.3 und PHP 8.2.

**Comment by heimseiten** [comment]
Leider schaffe ich es momentan nicht mich darum zu kümmern. Ich hoffe es in den nächsten Wochen korrigieren zu können.

**Comment by heimseiten** [comment]
Es wird vermutlich noch eine Zeit Weile dauern, bis ich Zeit finde. Sonst könntest du auch gerne einen Pull Request machen.

**Comment by heimseiten** [comment]
Wurde mit der Version 1.2.0 korrigiert.
